### ISSUE TITLE
Preparation for version 0.1.0

### ISSUE THREAD

**Issue by Marcelixoo** [the-library-guild/code-library-app#14]
## Overview

As we approach our first user testing session, we would like to get things ready for a dry run on campus. During this session, we'll cover the primary user flows agreed upon at our last meeting on Thu, 29 Sep. 2022.

> (1) As a student, I want to borrow a book from the physical library by scanning its QR code and landing on the relevant book page to proceed with the borrowing.

> (2) As a student, I want to check whether books recommended during LUs or quick chats are available in the physical library.

The scope of each feature will be distilled into their issues, but the overall goal is to have things done within the next two iterations (approximately 1 month from the time of writing). This includes the necessary infrastructure setup and any bureaucratic process involved in getting things running in a production environment accessible to any CODE student. Alex will be responsible for opening a ticket on CODE IT's ServiceDesk platform to document what's missing to get our app up and running under CODE cloud infrastructure. It is, therefore, the goal of this ticket to document the missing parts and make it clear what should be handled by us and what should be handled by the CODE IT support team.

## Roadmap

The following list reflects what's missing to prepare the app for user testing without special order or prioritization. Note that this is a first draft, which might change in the upcoming days.

- [ ] Define a simpler  (staging) deployment strategy for dry run tests on campus.
- [ ] Define an official deployment strategy using CODE's cloud infrastructure.
- [ ] Setup an official hostname for the app [www.library.code.berlin](http://library.code.berlin/)](http://library.code.berlin) (currently hosting a koha app).
- [ ] Adapt our codebase to use [the current spreadsheet](https://docs.google.com/spreadsheets/d/1Xv54lE3hS2kienJ3WwxOrcGo9z5A-DdX6d7k9BjUWdg/edit#gid=0) as a CMS (back office) accessible only to librarians and working students.
- [ ] Print out unofficial QR codes pointing to a staging environment where to run tests on campus.
- [ ] Print all necessary QR codes pointing to the official hostname and glue them into physical books.
